### ISSUE TITLE
JSON editor is not loading

### ISSUE THREAD

**Issue by earcos** [o10n-x/wordpress-javascript-optimization#1]
Found a new bug 😄 

All JSON editors are not loading (CSS and JS optimization plugins).

Here's a screenshot:

![screen shot 2018-03-13 at 19 48 30](https://user-images.githubusercontent.com/16387856/37363200-9970762c-26f7-11e8-8f3b-ff825af51c37.png)

As always, thanks a lot!

**Comment by optimalisatie** [comment]
Hi earcos,

Thank you very much for your time to provide feedback! It is very valuable!

Could you please let us know what browser you are using and if there is an error visible in the console?

**Comment by earcos** [comment]
Tried on Safari, Firefox, and Chrome. The only error I get on the console:

> Uncaught ReferenceError: O10N is not defined
> at tools.php?page=o10n-js&tab=delivery&t=1521029916:91

**Comment by optimalisatie** [comment]
The latest update contains the new script load method. Please let us know if the issue is resolved!

**Comment by earcos** [comment]
Tried again, but JSON editors are still not loading 😢

**Comment by optimalisatie** [comment]
Hi earcos,

Thank you very much for your feedback!

Do you have any idea what the cause could be?

We've tested it using www.crossbrowsertesting.com in old Safari, Opera, IE 10+, Android 4.4, iPhone 5 and it appears to work very well on all modern browsers.

![image](https://user-images.githubusercontent.com/8843669/37877343-1975ed8c-305a-11e8-89c4-f274511b9591.png)

![image](https://user-images.githubusercontent.com/8843669/37877441-b779d79a-305b-11e8-8aaa-3b3172f320f3.png)

**Comment by earcos** [comment]
No idea 😞 

I had the console open at all times, this time no errors. 

Maybe because we're using WordPress Multisite? 

Is the editor loaded from an external resource? Maybe there is some sort of security restriction in WordPress preventing the editor from being loaded?

**Comment by optimalisatie** [comment]
There are no external resources loaded. The JSON editor is is a popular and well developed editor:

https://github.com/josdejong/jsoneditor

Could you please let us know the browser name and version that you are using? Is the javascript and CSS editor working and are you able to use the advanced CSS minify options (on-off switches)?

**Comment by earcos** [comment]
I've tried on Safari latest versión (11.0.3), Chrome latest version (65.0.3325.162) and Firefox latest version (59.0.2).

A few screenshots of what is loading and what isn't. 

![screen shot 2018-03-27 at 15 27 08](https://user-images.githubusercontent.com/16387856/37970695-67b928a8-31d4-11e8-9077-75cfa89b203f.png)

![screen shot 2018-03-27 at 15 43 42](https://user-images.githubusercontent.com/16387856/37971226-b5f0b774-31d5-11e8-9d2d-eabd65c91beb.png)

![screen shot 2018-03-27 at 15 43 48](https://user-images.githubusercontent.com/16387856/37971235-bc95fe5e-31d5-11e8-87e3-796b348b6293.png)

**Comment by optimalisatie** [comment]
Hi earcos,

The plugins have been updated in the past months. No other users have reported this issue.

If you are still experiencing the UI issue, please let us know!

**Comment by gpcola** [comment]
I'm experiencing this same issue. All blocks where the JSON editor should show display only

`Loading JSON editor...`

Is there any resolution or potential conflicts that you are aware of? I'm just playing around with the WPO suite for the first time, and have a JS error that I can only solve by exclusion of the offending script file. Because the 'Async Config Filter' relies on the JSON editor I'm unable to do so.
