### ISSUE TITLE
Not able to see...

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-javascript-optimization#10]
![image](https://user-images.githubusercontent.com/21690761/40648986-c72d1d26-62fd-11e8-9652-90a3b8050e5c.png)

i'm not able to see what's are the 5 errors.

would be very usefull to make it show like a +/- to see more or less error.

**Comment by optimalisatie** [comment]
This is a restriction by JSON editor. You could request the feature at https://github.com/josdejong/jsoneditor

The schema's itself can be examined on https://github.com/o10n-x/wordpress-o10n-core/tree/master/schemas
