### ISSUE TITLE
readme/what's new

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-javascript-optimization#11]
Jan,

it would be great, if the readme or the change file would be updated with the history of a new release to see what was changed. Thanks.

**Comment by optimalisatie** [comment]
Hi Andreas,

Thank you very much for the feedback!

The latest update added a link to [Github Releases](https://github.com/o10n-x/wordpress-javascript-optimization/releases) (Version History) on the plugin overview.

![image](https://user-images.githubusercontent.com/8843669/41155578-e646f7c6-6b1e-11e8-955d-070ca491ce4a.png)

![image](https://user-images.githubusercontent.com/8843669/41156357-d434fbb6-6b21-11e8-8e7b-f654767dec4b.png)

**Comment by AlphaDE** [comment]
Great... thanks.
