### ISSUE TITLE
Can't async the jquery.js

### ISSUE THREAD

**Issue by azirer** [o10n-x/wordpress-javascript-optimization#14]
I can't async the jquery.js script.

I use so far only the delivery optimization and I have tried different load positions and of course the jQuery Stub enabled.
Inspecting the source code I can see the script inside the `data-o10n` variable
`data-o10n="[[ø],ø,ø,[[[1,"https:\/\/example.com\/wp-includes\/js\/jquery\/jquery.js?ver=1.12.4",null,null,null,null]....`

however while all other scripts are loaded just before `</body>` I see in the `<head>` 
`<script src="https://example.com/wp-includes/js/jquery/jquery.js?ver=1.12.4"></script>`

Google PSI reports it as render-blocking as well.

Also this is not visible in "right click -> view source" I see it only in the chrome developer tools  
`<script type="text/javascript" charset="utf-8" data-o10n="" async="" src="https://example.com/wp-includes/js/jquery/jquery.js?ver=1.12.4"></script>` 

I managed to async or defer (both choices are available) the jquery.js using the async scripts plugin from WP repo but I wanted to take my chances  with o10n javascript optimization.

Is there any specific configuration I should try? I can post my JSON configuration if that helps.

**Comment by optimalisatie** [comment]
Hi azirer,

The `data-o10n` attribute indicates that the script is added via the javascript proxy or that it is individually included as async script via the async configuration (while you may want to load the file concatenated with other scripts to bypass the Google PageSpeed performance issue).

If you want to separately load jQuery you could create a concat group specifically for jQuery related scripts, and add it as an dependency for other concat groups.

An example from another website: it matches jquery.js, some jQuery extensions and some global scripts in group `global` and all additional (potentially page specific) scripts are grouped in `additional` with dependency `global`.

```json
[
  {
    "match": [
      "jquery.js",
      {
        "string": "/jquery\\.(blockUI|lazyloadxt)/",
        "regex": true
      },
      "scripts/ytprefs",
      "scripts/lity",
      "js.cookie"
    ],
    "group": {
      "title": "Global",
      "key": "global"
    }
  },
  {
    "match": [
      {
        "string": "/^.*$/",
        "regex": true
      },
      "iconic-woothumbs/assets/frontend/js/main.js",
      "var wc_single_product_params"
    ],
    "group": {
      "title": "Additional",
      "key": "additional"
    },
    "dependency": "global"
  }
]
```

By using `O10N_DEBUG` in wp-config.php can display the performance of your configuration:

![image](https://user-images.githubusercontent.com/8843669/41356272-d8795748-6f23-11e8-8470-e1fed6c153cd.png)

An option is to set `O10N_DEBUG` based on a query string, e.g. `?debug` or based on developer IP's:

```php
// wp-config.php

/** enable o10n debug mode by query string */
if (isset($_GET['debug'])) {
  define('O10N_DEBUG', true);
}
```

**Comment by azirer** [comment]
Almost all of the scripts depend on jquery.js. So should I create one group just for the file jquery.js, name it **global** and add all other scripts in the group **additional** which depends on **global**? Will this allow the jquery.js to load async? I think it will not.

Can't I just not minify or concat any of the scripts and load all of them async including jquery.js? Let's suppose just for now that there are no inline jquery scripts in the html and the jquery stub could catch all the inline jquery scripts later. That;s what I was trying to do in the first place

**Comment by optimalisatie** [comment]
Yes, if your scripts are shared by each page, a single concat group (including jQuery) may be most efficient. Concat groups can be used to optimize the download size vs execution performance during navigation. 

For example, a contact form may require some scripts for Google maps. If you don't use a concat group configuration it would result in a complete new concatenated file, which may include +500kb in scripts that were already downloaded on a previous page. In this case you could create a group for the scripts that are shared between pages and create a second group for the contact page related scripts that loads after the 'global' concatenated script. 

If you want to get deeper into script optimization you can also have a look at script execution prioritization. It is possible to time the execution of individual scripts within a concatenated script, for example using a `domReady` callback, `requestIdleCallback` or element scrolled into view. This means that you can have essential scripts execute during the page load / render and other scripts with a lower priority, for example based on CPU availability (requestIdleCallback).

### Example: requestIdleCallback (1000ms exec window)
 
Here the execution of a concatenated script within concat group `global` is delayed using `requestIdleCallback` to wait for CPU availability, enabling to prioritize the execution of other more important scripts during the initial page render. 

As you can see, the script consumes `12ms` in CPU execution time making it a relatively heavy script that may unnecessarily get in the way of scripts essential for the optimal [Time To Interactive](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive) and [First Meaningful Paint](https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint).

Browser console:
![image](https://user-images.githubusercontent.com/8843669/41154186-a370616c-6b19-11e8-9904-db8ccb4192e3.png)

#### Example JSON (concat group)

```json
[
  {
    "match": [
      "jquery.js",
      {
        "string": "/jquery\\.(blockUI|lazyloadxt)/",
        "regex": true
      },
      "scripts/ytprefs",
      "scripts/lity",
      "js.cookie"
    ],
    "group": {
      "title": "Global",
      "key": "global"
    }
  },
  {
    "match": [
      {
        "string": "/^.*$/",
        "regex": true
      },
      "iconic-woothumbs/assets/frontend/js/main.js",
      "var wc_single_product_params"
    ],
    "group": {
      "title": "Additional",
      "key": "additional"
    },
    "dependency": "global"
  }
]
```

![image](https://user-images.githubusercontent.com/8843669/41160561-68e64b8a-6b30-11e8-91d0-1c800b19f25e.png)

#### Example JSON (async config filter)

```json
[
  {
    "match": "/\\/(lity|ytprefs|fitvids|jquery\\.flexslider)\\.js/",
    "regex": true,
    "async": true,
    "exec_timing": {
      "type": "requestIdleCallback",
      "timeout": 1000,
      "setTimeout": 100
    }
  }
]
```

![image](https://user-images.githubusercontent.com/8843669/41160523-499a5c12-6b30-11e8-8d90-e54d261c1704.png)
