### ISSUE TITLE
prevent js from loading on certain pages

### ISSUE THREAD

**Issue by ProductivePhysician** [o10n-x/wordpress-javascript-optimization#18]
Hi again,
I am wanting to block certain scripts from loading when on pages and only load on posts.
I imagine there is a way to do this using a functions.php script?
Could you give me any pointers?
Cheers

**Comment by optimalisatie** [comment]
Hi @ProductivePhysician,

Our apologies for the late reply!

The plugin provides multiple solutions that meet your specific requirement. There is the script capture proxy that could capture async injected scripts and for example delete them.

![image](https://user-images.githubusercontent.com/8843669/49580096-6ca02500-f94e-11e8-90b0-cc374badd9c3.png)

You could also use PHP conditions, e.g. `is_page`, and a WordPress filter to simply delete all scripts from the HTML. There are two filters:  `o10n_script_text_pre` and  `o10n_script_src_pre` (before processing of a script).

To ignore a script (i.e. to not touch it and leave it within the HTML) you would need to return the string `ignore`. To delete a script, you would need to return `delete`.

```php
// filter script src before processing
add_filter('o10n_script_src_pre', function($src) {
    if (strpos($src, 'script-name') !== false) {
        return 'ignore'; // leave script untouched in the HTML
    }

    // delete script from HTML
    // return 'delete';

    // apply or remove CDN url
    // return preg_replace('/regex/','modified',$src); 

    return $src; // important
}, 10, 1);
```

The `o10n_script_text_pre` filter enables to do the same for inline scripts. It enables to modify the inline script text and similarly, ignore a script or delete a script from the HTML.

### Conditional javascript optimization

What you may be interested in is fine grained custom javascript optimization for individual pages or page types. A recently added [Stealth Optimization Config Proxy](https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55) concept makes it possible. The provided concept enables to edit the plugin settings using physical `.json` files that can be loaded conditionally via a stealth optimization plugin proxy.

More information is in the release publication: https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55

Please let us know if you have other questions.
