### ISSUE TITLE
Feature suggestion: Selective js loading (like critical css)

### ISSUE THREAD

**Issue by ProductivePhysician** [o10n-x/wordpress-javascript-optimization#19]
Hi,
In the Critical CSS options we can enter the CSS files we want to load and we can use WordPress filters to enable them selectively.
Is there any way this could be done for js files?
Cheers!

**Comment by optimalisatie** [comment]
Thanks a lot for the question!

What you may be interested in is fine grained custom javascript optimization for individual pages or page types. A recently added [Stealth Optimization Config Proxy](https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55) concept makes it possible. The provided concept enables to edit the plugin settings using physical `.json` files that can be loaded conditionally via a stealth optimization plugin proxy.

More information is in the release publication: https://github.com/o10n-x/wordpress-http2-optimization/releases/tag/0.0.55
