### ISSUE TITLE
Seems to be breaking AMP

### ISSUE THREAD

**Issue by jiiins** [o10n-x/wordpress-javascript-optimization#2]
When either Code Optimization or Delivery Optimization is active, AMP pages stop working.

As a workaround I tried adding `if (is_amp_endpoint()) { return;}` at the beginning of javascript-optimization.php but it results in a 500 error.

So I had to disable it completely. Is there any other way?

PS: the same happens with the CSS plugin.

**Comment by optimalisatie** [comment]
Hi jiiins,

Thank you very much for your feedback!

You can disable the optimization by defining `define('O10N_DISABLED', true);` or using a WordPress filter:

```php
add_filter('o10n_disabled', function() { 
	
	# disable optimization for AMP pages
	if (is_amp_endpoint()) { return true; } 

	return false;
});
```

**Comment by jiiins** [comment]
Thanks. However, calling `is_amp_endpoint()` too early generates a 500 error and adding your filter too late has no effect! I can;t find the sweet spot... Any suggestions on where to add this?

**Comment by jiiins** [comment]
Could you please have a look? I guess I'm not the only one using AMP. Your previous version worked perfectly along AMP, so I guess you'd already know how to fix this?

Thanks

**Comment by optimalisatie** [comment]
Hi @jiiins,

Did you try the hook `template_redirect`?

**Comment by jiiins** [comment]
With this:
`add_action( 'template_redirect', 'my_page_template_redirect' );
function my_page_template_redirect(){
	if (is_amp_endpoint()) { 
		define('O10N_DISABLED', true);
	} 
}`

I get this error:
`array(4) { ["type"]=> int(8) ["message"]=> string(32) "Undefined variable: async_sheets" ["file"]=> string(92) "/www/site123/public/wp-content/plugins/css-optimization/controllers/css.class.php" ["line"]=> int(550) }`

**Comment by optimalisatie** [comment]
The latest update has an improved optimization status check. Could you please try again?

**Comment by jiiins** [comment]
I disabled all plugins. When I activate the CSS plugin, I can't see any minification/concatenation and the console says "Uncaught ReferenceError: o10n is not defined".

Plus this:
`Fatal error:  Uncaught Error: Call to a member function push() on boolean in /www/site123/public/wp-content/plugins/css-optimization/controllers/css.class.php:1923
Stack trace:
#0 /www/site123/public/wp-content/plugins/css-optimization/controllers/css.class.php(925): O10n\Css-&gt;url_filter('https://staging...')
#1 /www/site123/public/wp-includes/class-wp-hook.php(286): O10n\Css-&gt;process_html('&lt;!DOCTYPE html&gt;...')
#2 /www/site123/public/wp-includes/plugin.php(203): WP_Hook-&gt;apply_filters('&lt;!DOCTYPE html&gt;...', Array)
#3 /www/site123/public/wp-content/plugins/css-optimization/core/controllers/output.class.php(82): apply_filters('o10n_html_pre', '&lt;!DOCTYPE html&gt;...')
#4 [internal function]: O10n\Output-&gt;process_buffer('&lt;!DOCTYPE html&gt;...', 9)
#5 /www/site123/public/wp-includes/functions.php(3729): ob_end_flush()
#6 /www/site123/public/wp-includes/class-wp-hook.php(286): wp_ob_end_flush_all('')
#7 /www/site123/public/wp-includes/class-wp-hook. in <b>/www/site123/public/wp-content/plugins/css-optimization/controllers/css.class.php</b> on line <b>1923</b><br />`

**Comment by optimalisatie** [comment]
Hi jiiins,

Thank you very much for reporting this issue! 

The HTTP/2 Server Push configuration was still active after deactivating the HTTP/2 Optimization plugin.

The CSS and Javascript optimization plugins have been updated with a fix. Please let us know if this resolves the issue!

**Comment by jiiins** [comment]
Now CSS works again for regualr pages, but still breaks AMP.

Also, `Uncaught ReferenceError: o10n is not defined` appears for the JS plugin too.

**Comment by optimalisatie** [comment]
Hi jiiins, 

The plugin is at version `0.0.68` and was recently updated to be compatible with AMP. Please see the following topic:

https://github.com/o10n-x/wordpress-javascript-optimization/issues/9
