### ISSUE TITLE
Latest version of Javascript Optimization?

### ISSUE THREAD

**Issue by KevinPlusPlus** [o10n-x/wordpress-javascript-optimization#4]
Hello,

I  just started using your plugins last week and am really sad to hear about this issue with WordPress.

I am comfortable downloading and installing from Github, and I successfully grabbed the latest versions of the HTTP2 and CSS optimization plugins.

However, it looks like the version of Javascript Optimization on Github is several versions prior to the version that was on the WordPress repository last week (I have 0.0.41 vs 0.0.25 on the repository), and the most recent updates showing are 23 days old.

Is there a way to get the latest updates? WordPress had been advising updates before the plugins were removed.

Thank you,

Kevin

**Comment by optimalisatie** [comment]
Hi Kevin,

Thank you for your feedback! For some reason the recent updates weren't pushed on Github. 

The latest update has just been published.
